### ISSUE TITLE
RootCA support

### ISSUE THREAD

**Issue by mixmind** [resgateio/resgate#177]
Hi, I have self signed certificate. 

There is no option to add rootCA to resgate, or I'm missing something?

These error I receive:
`2020/11/09 12:33:12.016277 [ERR] Problem encountered: x509: certificate signed by unknown authority`

**Comment by jirenius** [comment]
Resgate currently doesn't support adding rootCA to be used when connecting to NATS over TLS.

Next minor release (v1.7.0) will include this support.

**Comment by jirenius** [comment]
Resolved in PR #206
