### ISSUE TITLE
image permission

### ISSUE THREAD

**Issue by pjebs** [resgateio/resgate#180]
![image](https://user-images.githubusercontent.com/5377970/104541576-f9615500-5675-11eb-9613-048a37467fc3.png)

I came across your image.
Can I use it in the readme of a Go package I'm about to make and opensource?

**Comment by jirenius** [comment]
Hi,

Yes, you can use it for a readme for an opensource Go project with the conditions:
* Credit Renee French for the Go gopher
* Credit Samuel Jirénius (me! :) ) for the illustration

Best regards,
Samuel

**Comment by pjebs** [comment]
Thanks,
It'll be for: https://github.com/rocketlaunchr/go-pool
