### ISSUE TITLE
Forward Query from collection request to model request.

### ISSUE THREAD

**Issue by jurgisk** [resgateio/resgate#196]
Hi.
Would it be possible to forward the request query string made to collection resource to each individual resource that the collection points to?
That's for the none-soft types of resource id's.

Or maybe there is currently a way to forward this information already?

Many thanks,
Jurgis

**Comment by jirenius** [comment]
Late reply, but yes.

A resource reference may contain reference to any type of resource, including query resources.
That means you can include in the _rid_ any query string; the same as provided to your collection, or completely different ones.

Example response to a query collection _get request_:

```json
{
    "collection": [
        { "rid": "example.model?foo=b" },
        { "rid": "example.model?foo=a" },
        { "rid": "example.model?foo=r" },
    ],
    "query": "foo=bar"
}
```

**Comment by jirenius** [comment]
Closing as the requested functionality exists.
